import FeatureCard from "../FeatureCard/FeatureCard";
import {
  FaFileAlt,
  FaChartLine,
  FaMicrophone,
  FaRobot,
  FaFilePdf,
  FaUserTie,
} from "react-icons/fa";

function Features() {
  return (
    <section className="bg-slate-950 py-28 text-white">

      <div className="mx-auto max-w-7xl px-8">

        <div className="mb-16 text-center">

          <p className="mb-4 font-semibold uppercase tracking-widest text-violet-400">
            Features
          </p>

          <h2 className="mb-6 text-5xl font-bold">
            Everything You Need
          </h2>

          <p className="mx-auto max-w-2xl text-lg text-slate-400">
            InterviewGPT helps you analyze your resume, improve your ATS score,
            practice interviews and prepare for your dream job.
          </p>

        </div>

        <div className="grid gap-8 md:grid-cols-2 lg:grid-cols-3">

          <FeatureCard
            icon={<FaFileAlt className="text-violet-400" />}
            title="Resume Analysis"
            description="AI scans your resume and highlights strengths, weaknesses and improvement areas."
          />

          <FeatureCard
            icon={<FaChartLine className="text-blue-400" />}
            title="ATS Score"
            description="Check how ATS-friendly your resume is with an accurate compatibility score."
          />

          <FeatureCard
            icon={<FaRobot className="text-pink-400" />}
            title="AI Interview"
            description="Practice real interview questions generated by AI based on your resume."
          />

          <FeatureCard
            icon={<FaMicrophone className="text-green-400" />}
            title="Voice Analysis"
            description="Improve communication, confidence and speaking skills with AI feedback."
          />

          <FeatureCard
            icon={<FaFilePdf className="text-red-400" />}
            title="PDF Report"
            description="Download a detailed report with ATS score, resume suggestions and interview tips."
          />

          <FeatureCard
            icon={<FaUserTie className="text-yellow-400" />}
            title="Career Guidance"
            description="Receive personalized career suggestions and skill recommendations."
          />

        </div>

      </div>

    </section>
  );
}

export default Features;